// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe8oNE8HR7iUtOl-diIxHw8v_d7fXJLYg',
    appId: '1:633070267511:web:9467321690498b1e7a2a72',
    messagingSenderId: '633070267511',
    projectId: 'kitafit-ba016',
    authDomain: 'kitafit-ba016.firebaseapp.com',
    storageBucket: 'kitafit-ba016.firebasestorage.app',
    measurementId: 'G-S81VMLHY3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHq9Q0c_0OaseGURo81fxp0-NblL-VY-Y',
    appId: '1:633070267511:android:8f7d07dcd52ef9957a2a72',
    messagingSenderId: '633070267511',
    projectId: 'kitafit-ba016',
    storageBucket: 'kitafit-ba016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8h6B1sf08ya2E4pcqvI3iLRSDbGfrm88',
    appId: '1:633070267511:ios:10548f8b163671cb7a2a72',
    messagingSenderId: '633070267511',
    projectId: 'kitafit-ba016',
    storageBucket: 'kitafit-ba016.firebasestorage.app',
    iosBundleId: 'com.example.todoCleanBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8h6B1sf08ya2E4pcqvI3iLRSDbGfrm88',
    appId: '1:633070267511:ios:10548f8b163671cb7a2a72',
    messagingSenderId: '633070267511',
    projectId: 'kitafit-ba016',
    storageBucket: 'kitafit-ba016.firebasestorage.app',
    iosBundleId: 'com.example.todoCleanBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe8oNE8HR7iUtOl-diIxHw8v_d7fXJLYg',
    appId: '1:633070267511:web:8f26710cf5e9f2677a2a72',
    messagingSenderId: '633070267511',
    projectId: 'kitafit-ba016',
    authDomain: 'kitafit-ba016.firebaseapp.com',
    storageBucket: 'kitafit-ba016.firebasestorage.app',
    measurementId: 'G-FCMYGWH954',
  );

}