// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-iy2sY7Il-BKLfavVrEJ3aENaILhnoso',
    appId: '1:732705692282:web:4ce77be27400f11da439c3',
    messagingSenderId: '732705692282',
    projectId: 'kitafit-c0a1e',
    authDomain: 'kitafit-c0a1e.firebaseapp.com',
    storageBucket: 'kitafit-c0a1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIo8Q-5HReUSH37K6QH_aYSCFpoHsuqRQ',
    appId: '1:732705692282:android:01a17e0100d74105a439c3',
    messagingSenderId: '732705692282',
    projectId: 'kitafit-c0a1e',
    storageBucket: 'kitafit-c0a1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMedUfCfpoCkAXH7bbZd_7r3-vicGeS2A',
    appId: '1:732705692282:ios:338fd351892da44ba439c3',
    messagingSenderId: '732705692282',
    projectId: 'kitafit-c0a1e',
    storageBucket: 'kitafit-c0a1e.firebasestorage.app',
    iosBundleId: 'com.example.todoCleanBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMedUfCfpoCkAXH7bbZd_7r3-vicGeS2A',
    appId: '1:732705692282:ios:338fd351892da44ba439c3',
    messagingSenderId: '732705692282',
    projectId: 'kitafit-c0a1e',
    storageBucket: 'kitafit-c0a1e.firebasestorage.app',
    iosBundleId: 'com.example.todoCleanBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-iy2sY7Il-BKLfavVrEJ3aENaILhnoso',
    appId: '1:732705692282:web:2b326332d6306024a439c3',
    messagingSenderId: '732705692282',
    projectId: 'kitafit-c0a1e',
    authDomain: 'kitafit-c0a1e.firebaseapp.com',
    storageBucket: 'kitafit-c0a1e.firebasestorage.app',
  );
}
